<?php

return [
    'fonts' => [
        // PDF default supported fonts
        ['font-family' => 'DejaVu Sans', 'provider' => ''],
        ['font-family' => 'Helvetica', 'provider' => ''],
        ['font-family' => 'Times', 'provider' => ''],

        // Custom fonts
        ['font-family' => "'Nanum Gothic', sans-serif", 'provider' => 'google'], // Korean

        // Content editor fonts
        ['font-family' => 'Arial, sans-serif', 'provider' => ''],
        ['font-family' => 'courier', 'provider' => ''],
        ['font-family' => 'Georgia, serif', 'provider' => ''],
        ['font-family' => 'monospace', 'provider' => ''],
        ['font-family' => 'sans-serif', 'provider' => ''],
        ['font-family' => 'serif', 'provider' => ''],
        ['font-family' => 'Abel, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Abril Fatface', 'provider' => 'google'],
        ['font-family' => 'Advent Pro, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Aladin, cursive', 'provider' => 'google'],
        ['font-family' => 'Alegreya, serif', 'provider' => 'google'],
        ['font-family' => 'Alegreya Sans SC, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Alegreya SC, serif', 'provider' => 'google'],
        ['font-family' => 'Alice, serif', 'provider' => 'google'],
        ['font-family' => 'Allerta Stencil, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Allura, cursive', 'provider' => 'google'],
        ['font-family' => 'Almendra Display, cursive', 'provider' => 'google'],
        ['font-family' => 'Amatic SC, cursive', 'provider' => 'google'],
        ['font-family' => 'Andika, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Anonymous Pro, monospace', 'provider' => 'google'],
        ['font-family' => 'Architects Daughter, cursive', 'provider' => 'google'],
        ['font-family' => 'Arimo, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Arsenal, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Assistant', 'provider' => 'google'],
        ['font-family' => 'Aubrey, cursive', 'provider' => 'google'],
        ['font-family' => 'Anton, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Archivo Narrow, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Bad Script, cursive', 'provider' => 'google'],
        ['font-family' => 'BenchNine, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Bevan, cursive', 'provider' => 'google'],
        ['font-family' => 'Bigelow Rules, cursive', 'provider' => 'google'],
        ['font-family' => 'Bilbo, cursive', 'provider' => 'google'],
        ['font-family' => 'Bonbon, cursive', 'provider' => 'google'],
        ['font-family' => 'Bowlby One SC, cursive', 'provider' => 'google'],
        ['font-family' => 'Cabin Condensed, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Carrois Gothic SC, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Caveat, cursive', 'provider' => 'google'],
        ['font-family' => 'Chewy, cursive', 'provider' => 'google'],
        ['font-family' => 'Cinzel, serif', 'provider' => 'google'],
        ['font-family' => 'Comfortaa, cursive', 'provider' => 'google'],
        ['font-family' => 'Concert One, cursive', 'provider' => 'google'],
        ['font-family' => 'Cormorant, serif', 'provider' => 'google'],
        ['font-family' => 'Cormorant Garamond, serif', 'provider' => 'google'],
        ['font-family' => 'Cormorant Infant, serif', 'provider' => 'google'],
        ['font-family' => 'Cormorant SC, serif', 'provider' => 'google'],
        ['font-family' => 'Cormorant Unicase, serif', 'provider' => 'google'],
        ['font-family' => 'Cousine', 'provider' => 'google'],
        ['font-family' => 'Crafty Girls, cursive', 'provider' => 'google'],
        ['font-family' => 'Cuprum, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Cutive Mono, monospace', 'provider' => 'google'],
        ['font-family' => 'Devonshire, cursive', 'provider' => 'google'],
        ['font-family' => 'Didact Gothic, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Diplomata SC, cursive', 'provider' => 'google'],
        ['font-family' => 'Dosis, sans-serif', 'provider' => 'google'],
        ['font-family' => 'EB Garamond, serif', 'provider' => 'google'],
        ['font-family' => 'El Messiri, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Elsie, cursive', 'provider' => 'google'],
        ['font-family' => 'Encode Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Exo, sans-serif', 'provider' => 'google'],
        ['font-family' => "'Exo 2', sans-serif", 'provider' => 'google'],
        ['font-family' => 'Felipa, cursive', 'provider' => 'google'],
        ['font-family' => 'Fira Code, monospace', 'provider' => 'google'],
        ['font-family' => 'Fira Mono, monospace', 'provider' => 'google'],
        ['font-family' => 'Fira Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Fira Sans Condensed, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Fira Sans Extra Condensed, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Fjalla One, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Forum, cursive', 'provider' => 'google'],
        ['font-family' => 'Frank Ruhl Libre', 'provider' => 'google'],
        ['font-family' => 'Fredericka the Great, cursive', 'provider' => 'google'],
        ['font-family' => 'Gabriela, serif', 'provider' => 'google'],
        ['font-family' => 'Gilda Display, serif', 'provider' => 'google'],
        ['font-family' => 'Give You Glory, cursive', 'provider' => 'google'],
        ['font-family' => 'Gruppo, cursive', 'provider' => 'google'],
        ['font-family' => 'Handlee, cursive', 'provider' => 'google'],
        ['font-family' => 'Happy Monkey, cursive', 'provider' => 'google'],
        ['font-family' => 'Hind', 'provider' => 'google'],
        ['font-family' => 'IBM Plex Mono, monospace', 'provider' => 'google'],
        ['font-family' => 'IBM Plex Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'IBM Plex Serif, serif', 'provider' => 'google'],
        ['font-family' => 'Iceland, cursive', 'provider' => 'google'],
        ['font-family' => 'Inconsolata, monospace', 'provider' => 'google'],
        ['font-family' => 'Josefin Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Istok Web, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Julee, cursive', 'provider' => 'google'],
        ['font-family' => 'Julius Sans One, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Junge, serif', 'provider' => 'google'],
        ['font-family' => 'Jura, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Just Me Again Down Here, cursive', 'provider' => 'google'],
        ['font-family' => 'Kaushan Script, cursive', 'provider' => 'google'],
        ['font-family' => 'Kelly Slab, cursive', 'provider' => 'google'],
        ['font-family' => 'Kite One, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Kosugi, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Kosugi Maru, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Kurale, serif', 'provider' => 'google'],
        ['font-family' => 'Lato, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Ledger, serif', 'provider' => 'google'],
        ['font-family' => 'Lekton, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Life Savers, cursive', 'provider' => 'google'],
        ['font-family' => 'Literata, serif', 'provider' => 'google'],
        ['font-family' => 'Lobster, cursive', 'provider' => 'google'],
        ['font-family' => 'Lobster Two, cursive', 'provider' => 'google'],
        ['font-family' => 'Londrina Shadow, cursive', 'provider' => 'google'],
        ['font-family' => 'Lora, serif', 'provider' => 'google'],
        ['font-family' => 'Lovers Quarrel, cursive', 'provider' => 'google'],
        ['font-family' => "'M PLUS 1p', sans-serif", 'provider' => 'google'],
        ['font-family' => "'M PLUS Rounded 1c', sans-serif", 'provider' => 'google'],
        ['font-family' => 'Macondo, cursive', 'provider' => 'google'],
        ['font-family' => 'Marcellus SC, serif', 'provider' => 'google'],
        ['font-family' => 'Marck Script, cursive', 'provider' => 'google'],
        ['font-family' => 'Martel, serif', 'provider' => 'google'],
        ['font-family' => 'Maven Pro, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Merriweather, serif', 'provider' => 'google'],
        ['font-family' => 'Merriweather Sans', 'provider' => 'google'],
        ['font-family' => 'Mogra, cursive', 'provider' => 'google'],
        ['font-family' => 'Monoton, cursive', 'provider' => 'google'],
        ['font-family' => 'Montez, cursive', 'provider' => 'google'],
        ['font-family' => 'Montserrat, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Montserrat Alternates, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Montserrat Subrayada, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Neucha, cursive', 'provider' => 'google'],
        ['font-family' => 'Neuton, serif', 'provider' => 'google'],
        ['font-family' => 'Nixie One, cursive', 'provider' => 'google'],
        ['font-family' => 'Nothing You Could Do, cursive', 'provider' => 'google'],
        ['font-family' => 'Noto Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Noto Sans SC, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Noto Serif, serif', 'provider' => 'google'],
        ['font-family' => 'Noto Serif TC, serif', 'provider' => 'google'],
        ['font-family' => 'Nunito, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Old Standard TT, serif', 'provider' => 'google'],
        ['font-family' => 'Open Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Oranienbaum, serif', 'provider' => 'google'],
        ['font-family' => 'Oswald, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Oxygen, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Pacifico, cursive', 'provider' => 'google'],
        ['font-family' => 'Pangolin, cursive', 'provider' => 'google'],
        ['font-family' => 'Passion One, cursive', 'provider' => 'google'],
        ['font-family' => 'Pathway Gothic One, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Pattaya, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Petit Formal Script, cursive', 'provider' => 'google'],
        ['font-family' => 'Philosopher, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Play, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Playfair Display, serif', 'provider' => 'google'],
        ['font-family' => 'Playfair Display SC, serif', 'provider' => 'google'],
        ['font-family' => 'Podkova, serif', 'provider' => 'google'],
        ['font-family' => 'Poiret One, cursive', 'provider' => 'google'],
        ['font-family' => 'Pompiere, cursive', 'provider' => 'google'],
        ['font-family' => 'Poppins, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Prata, serif', 'provider' => 'google'],
        ['font-family' => "'Press Start 2P', cursive", 'provider' => 'google'],
        ['font-family' => 'Prosto One, cursive', 'provider' => 'google'],
        ['font-family' => 'PT Mono, monospace', 'provider' => 'google'],
        ['font-family' => 'PT Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'PT Sans Caption, sans-serif', 'provider' => 'google'],
        ['font-family' => 'PT Sans Narrow, sans-serif', 'provider' => 'google'],
        ['font-family' => 'PT Serif, serif', 'provider' => 'google'],
        ['font-family' => 'PT Serif Caption, serif', 'provider' => 'google'],
        ['font-family' => 'Quattrocento Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Quattrocento, serif', 'provider' => 'google'],
        ['font-family' => 'Quicksand, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Qwigley, cursive', 'provider' => 'google'],
        ['font-family' => 'Raleway, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Raleway Dots, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Redressed, cursive', 'provider' => 'google'],
        ['font-family' => 'Ribeye Marrow, cursive', 'provider' => 'google'],
        ['font-family' => 'Righteous, cursive', 'provider' => 'google'],
        ['font-family' => 'Roboto, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Roboto Condensed, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Roboto Mono, monospace', 'provider' => 'google'],
        ['font-family' => 'Roboto Slab, serif', 'provider' => 'google'],
        ['font-family' => 'Rochester, cursive', 'provider' => 'google'],
        ['font-family' => 'Rouge Script, cursive', 'provider' => 'google'],
        ['font-family' => 'Rubik, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Rubik Mono One, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Ruslan Display, cursive', 'provider' => 'google'],
        ['font-family' => 'Russo One, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Sacramento, cursive', 'provider' => 'google'],
        ['font-family' => 'Sanchez, serif', 'provider' => 'google'],
        ['font-family' => 'Satisfy, cursive', 'provider' => 'google'],
        ['font-family' => 'Sawarabi Gothic, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Scada, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Seaweed Script, cursive', 'provider' => 'google'],
        ['font-family' => 'Seymour One, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Shadows Into Light Two, cursive', 'provider' => 'google'],
        ['font-family' => 'Six Caps, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Snowburst One, cursive', 'provider' => 'google'],
        ['font-family' => 'Source Code Pro, monospace', 'provider' => 'google'],
        ['font-family' => 'Source Sans Pro, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Special Elite, cursive', 'provider' => 'google'],
        ['font-family' => 'Spectral, serif', 'provider' => 'google'],
        ['font-family' => 'Spectral SC, serif', 'provider' => 'google'],
        ['font-family' => 'Squada One, cursive', 'provider' => 'google'],
        ['font-family' => 'Stalinist One, cursive', 'provider' => 'google'],
        ['font-family' => 'Stint Ultra Expanded, cursive', 'provider' => 'google'],
        ['font-family' => 'Syncopate, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Tangerine, cursive', 'provider' => 'google'],
        ['font-family' => 'Tenor Sans, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Tinos, serif', 'provider' => 'google'],
        ['font-family' => 'Ubuntu, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Ubuntu Condensed, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Ubuntu Mono, monospace', 'provider' => 'google'],
        ['font-family' => 'Underdog, cursive', 'provider' => 'google'],
        ['font-family' => 'UnifrakturMaguntia, cursive', 'provider' => 'google'],
        ['font-family' => 'Vast Shadow, cursive', 'provider' => 'google'],
        ['font-family' => 'Viga, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Vollkorn, serif', 'provider' => 'google'],
        ['font-family' => 'Vollkorn SC, serif', 'provider' => 'google'],
        ['font-family' => 'Voltaire, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Wire One, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Yanone Kaffeesatz, sans-serif', 'provider' => 'google'],
        ['font-family' => 'Yeseva One, cursive', 'provider' => 'google'],
    ],
];
